controller_list:
  - name: "egm/joint_trajectory_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]

trajectory_execution:
  allowed_execution_duration_scaling: 2.0 # 1.2
  allowed_goal_duration_margin: 1.5 # 0.5
  allowed_start_tolerance: 0.01 # 0.02
